# frozen_string_literal: true

AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - '*.gemspec'

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Naming/PredicateMethod:
  Enabled: false

Gemspec/DevelopmentDependencies:
  Enabled: false