name: Publish Gem

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'
        bundler-cache: true
    
    - name: Run tests
      run: bundle exec rspec
    
    - name: Run RuboCop
      run: bundle exec rubocop
    
    - name: Build gem
      run: gem build dsfr_accessible_skip_links.gemspec
    
    - name: Publish to RubyGems
      run: |
        mkdir -p ~/.gem
        echo ":rubygems_api_key: ${RUBYGEMS_API_KEY}" > ~/.gem/credentials
        chmod 600 ~/.gem/credentials
        gem push dsfr_accessible_skip_links-*.gem
      env:
        RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}